version: '3.9'
name: typescript-todo-list
services:
  frontend:
    container_name: todo-frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app/frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: todo-backend
    build: ./backend
    ports:
      - 8000:8000
    platform: linux/x86_64
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env/
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8000"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: todo-db
    platform: linux/x86_64
    volumes:
      - .db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
